services:
  cinder-back:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
      - ../cinder-assets:/var/www/cinder-assets
    ports:
      - "8000:80"
    depends_on:
      - cinder-mysql
    networks:
      - cinder-network

  cinder-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cinder
      MYSQL_USER: cinder_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - cinder-network

  cinder-front:
    build:
      context: ../cinder-front
      dockerfile: Dockerfile
    volumes:
      - ../cinder-front:/app
    ports:
      - "5173:5173"
    networks:
      - cinder-network

  cinder-vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: cinder-vnc
    ports:
      - "5901:5900"
    volumes:
      - ./shared:/home/ubuntu/shared
    environment:
      - USER=ubuntu
      - PASSWORD=ubuntu
    restart: unless-stopped
    networks:
      - cinder-network

volumes:
  mysql_data:
  shared:

networks:
  cinder-network:
