services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
      - ../setta-assets:/var/www/setta-assets
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - setta-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: setta
      MYSQL_USER: setta_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - setta-network

  setta-front:
    build:
      context: ../setta-front
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ../setta-front:/app
    ports:
      - "5173:5173"
    networks:
      - setta-network

  ubuntu-vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: ubuntu-vnc
    ports:
      - "5900:5900"
    volumes:
      - ./shared:/home/ubuntu/shared
    environment:
      - USER=ubuntu
      - PASSWORD=ubuntu
    restart: unless-stopped
    networks:
      - setta-network

volumes:
  mysql_data:
  shared:

networks:
  setta-network:
